name: Image Request
description: Request a new image or modification to an existing image
title: "[Image Request]: "
labels: ["image request"]
body:
  - type: markdown
    attributes:
      value: |
          Before opening new issue, make sure there are no existing requests by searching the [repository issues](https://github.com/software-noob/pterodactyl-images/issues?q=label%3A%22image+request%22+).
  - type: dropdown
    id: expand
    attributes:
      label: Does this apply to existing image
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: image-name
    attributes:
      label: What's the image for (e.g. NodeJS, Dotnet, Shenandoah, etc)
      placeholder: NodeJS, Dotnet, Shenandoah, etc
    validations:
      required: true
  - type: textarea
    id: image-request
    attributes:
      label: Image Request
      description: Provide changes you are proposing
      placeholder: |
        Example 1

        The sourcemod image should have X dependency installed for Y plugin that requires it as documented here: https://docs.example.com

        Example 2

        New Node version has been released and I would like to have it available in the image
    validations:
      required: true
